site_name: Mean-Motion Resonances
site_url: https://github.com/smirik/resonances
repo_url: https://github.com/smirik/resonances
site_description: The python package that identifies two-body and three-body mean-motion resonances.
edit_uri: blob/master/docs/

theme:
        name: readthedocs
        include_homepage_in_sidebar: True
nav:
        - Home: index.md
        - "Getting Started":
                  - "Quick start": "quick-start.ipynb"
                  - "Installation and updates": "install.md"
                  - "Examples": "examples.ipynb"
        - "Features":
                  - "Simulations, Bodies, MMRs": core.ipynb
                  - "Libration module": libration.md
                  - "Resonance Matrices": matrix.md
                  - "Config": config.md
        - "About":
                  - "Copyright, license, references": about.md

plugins:
        - mkdocs-jupyter
          # include_source: True
          # execute: True
